version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
    versioning-strategy: lockfile-only
    reviewers:
      - 'kunalnagar'
    commit-message:
      prefix: 'chore'
      include: 'scope'
