os: linux
dist: xenial
language: node_js
node_js:
  - 8.10.0
before_install:
  - sudo add-apt-repository -y ppa:wine/wine-builds && sudo apt-get update && sudo apt-get install -y --install-recommends winehq-devel && sudo apt-get install -y fakeroot
cache:
  npm: true
script:
  - npm run deploy
if: tag IS present
deploy:
  provider: releases
  on:
    tags: true
  token: $GITHUB_TOKEN
  file_glob: true
  file: release-builds/*.zip
