os: linux
dist: xenial
language: node_js
node_js:
  - 12.18.1
before_install:
  - sudo add-apt-repository -y ppa:wine/wine-builds
  - sudo apt-get update
  - sudo apt-get install -y --install-recommends winehq-devel
  - sudo apt-get install -y fakeroot
jobs:
  include:
    - script: npm run build
    - if: branch = master
      deploy:
        provider: releases
        on:
          tags: true
        token: $GITHUB_TOKEN
        file_glob: true
        file: release-builds/*.zip
