on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install wine
        run: |
          sudo apt-get update
          sudo apt-get install -y wine64
          sudo apt-get install -y fakeroot
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
      - name: Upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: release-builds
          path: release-builds/*.zip
