name: Continuous Deployment

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Release
        run: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_UPLOAD_TOKEN }}
