name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install wine
        run: |
          sudo apt-get update
          sudo apt-get install -y wine64
          sudo apt-get install -y fakeroot
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
      - name: Create release
        id: create_release
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: true
      - name: Upload Release Assets
        if: startsWith(github.ref, 'refs/tags/')
        uses: csexton/release-asset-action@v2
        with:
          pattern: 'release-builds/*.zip'
          github-token: ${{ secrets.GITHUB_TOKEN }}
