name: Release encrypt0r

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Install windows dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          wget -qO- https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo apt install software-properties-common
          sudo apt-add-repository 'deb http://dl.winehq.org/wine-builds/ubuntu/ bionic main'
          wget -qO- https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/Release.key | sudo apt-key add -
          sudo sh -c 'echo "deb https://download.opensuse.org/repositories/Emulators:/Wine:/Debian/xUbuntu_18.04/ ./" > /etc/apt/sources.list.d/obs.list'
          sudo apt update
          sudo apt-get install -y --install-recommends winehq-devel
          sudo apt-get install -y fakeroot
      - name: Create release files
        run: yarn release
      - name: Upload release files
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release-builds/*.zip
          tag: ${{ github.ref }}
          file_glob: true
